TEMP_DIR = 'temp_dir'
RDNA_REF_HUMAN = 'references/bwa/human_rDNA.fa'
RDNA_REF_HUMAN_COD = 'references/bwa/human_rDNA_only_coding.fa'
RDNA_REF_HUMAN_SHIFTED = 'references/bwa/shifed_hrDNA.fa'
RDNA_REF_MOUSE = 'references/bwa/mouse_vlad1.fa'
